### ISSUE TITLE
Relationship field doesn't appear to be unmarshalled?

### ISSUE THREAD

**Issue by darrenparkinson** [forcedotcom/go-soql#32]
Hi,

I'm quite new to SOQL and I suspect I'm doing something wrong, but when I try to unmarshal a relationship field, it doesn't seem to work.

Essentially, I'm retrieving an account and wish to get the owner name.  Having the following creates the correct SOQL query:

```go
type Account struct {
	Name              string `soql:"selectColumn,fieldName=Name" json:"Name"`
	OwnerName         string `soql:"selectColumn,fieldName=Owner.Name" json:"OwnerName"`
}
```
Resulting in this SOQL:
```
SELECT Name,Owner.Name FROM Account
```

The owner name is in the raw response but does not appear in the OwnerName field.  I was assuming that given the SOQL query is correct, and the response contains the data, that this should unmarshal correctly?  Do I actually need to create an Owner struct with it's own SelectClause and selectColumn values for this to work?

Thanks for any assistance.

**Comment by atulkc** [comment]
@darrenparkinson Yes, that is correct. Even though `go-soql` is able to marshal the soql query correctly, if you need to unmarshal the returned payload in to your go struct then you will need to declare a `Owner` struct. This is because the json payload that is returned is a nested object (in this case `Owner` will be nested in `Account`).

It will look something like this:
```
type Account struct {
	Name          string `soql:"selectColumn,fieldName=Name" json:"Name"`
	Owner         string `soql:"selectColumn,fieldName=Owner" json:"Owner"`
}

type Owner struct {
	Name              string `soql:"selectColumn,fieldName=Name" json:"Name"`
}
```
This is as described [here](https://github.com/forcedotcom/go-soql#relationships) for child to parent relationship. This will result in same SOQL but allow you to unmarshal the result into your go structs.

**Comment by darrenparkinson** [comment]
Hi. Many thanks for the response. 

I realised after thinking about it some more that it was a pretty stupid question 😳, then I saw your response this morning which confirmed it. 

My thoughts were that essentially this library is for constructing/marshalling the soql and preventing injection attacks, not for unmarshalling json (there’s already a library for that 😆). 

Thanks again for the response, I’ll give that a go this morning.
